# Generated by Django 3.0.4 on 2020-07-20 12:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_os_weight_and_shortcut'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulsimAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('root', 'path', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LucasAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('root', 'path', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MsdkAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('root', 'path', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='OsAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('root', 'path', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('root', 'path', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Simics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='fulsim_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FulsimAsset'),
        ),
        migrations.AddField(
            model_name='result',
            name='lucas_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.LucasAsset'),
        ),
        migrations.AddField(
            model_name='result',
            name='msdk_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MsdkAsset'),
        ),
        migrations.AddField(
            model_name='result',
            name='os_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.OsAsset'),
        ),
        migrations.AddField(
            model_name='result',
            name='scenario_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ScenarioAsset'),
        ),
        migrations.AddField(
            model_name='result',
            name='simics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Simics'),
        ),
        migrations.AddField(
            model_name='driver',
            name='build_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
