# Generated by Django 3.0.4 on 2020-07-31 11:18

import os
import tempfile
import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feature_mapping_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('done', 'Done')], default='pending', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.FilePathField(default=os.path.join(tempfile.gettempdir(), 'xlsx'), path=api.models.xlsx)),
                ('requester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
