# Generated by Django 3.0.4 on 2020-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200327_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultgroup',
            name='alt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resultgroup',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resultgroup',
            name='mask',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
