# Generated by Django 3.0.4 on 2020-08-10 14:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_import_job_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='additional_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
