# Generated by Django 3.0.4 on 2020-08-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fix_importjob_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='os',
            options={'verbose_name_plural': 'Oses'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
