# Generated by Django 3.0.4 on 2020-08-21 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_verifier', '0004_auto_20200817_1706'),
        ('api', '0008_add_plural_names'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='featuremappingrule',
            name='unique_featuremappingrule_composite_constraint',
        ),
        migrations.AddField(
            model_name='featuremappingrule',
            name='codec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_verifier.Codec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuremappingrule',
            name='ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='featuremappingrule',
            constraint=models.UniqueConstraint(fields=('milestone', 'codec', 'feature', 'scenario', 'mapping', 'ids'), name='unique_featuremappingrule_composite_constraint_with_ids'),
        ),
        migrations.AddConstraint(
            model_name='featuremappingrule',
            constraint=models.UniqueConstraint(condition=models.Q(ids=None), fields=('milestone', 'codec', 'feature', 'scenario', 'mapping'), name='unique_featuremappingrule_composite_constraint_without_ids'),
        ),
    ]
