# Generated by Django 3.0.4 on 2020-09-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_fk_on_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_composite_constraint',
        ),
        migrations.AddField(
            model_name='item',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TestScenario'),
        ),
        migrations.AddField(
            model_name='item',
            name='test_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='plugin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='api.Plugin'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'args', 'plugin', 'scenario', 'test_id'), name='unique_item_composite_constraint'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('test_id', None), ('scenario', None), ('plugin', None)), fields=('name', 'args'), name='unique_item_composite_constraint_with_all_nulls'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('scenario', None), ('test_id', None)), fields=('name', 'args', 'plugin'), name='unique_item_composite_constraint_with_scen_id_nulls'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('plugin', None), ('test_id', None)), fields=('name', 'args', 'scenario'), name='unique_item_composite_constraint_with_plugin_id_nulls'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('plugin', None), ('scenario', None)), fields=('name', 'args', 'test_id'), name='unique_item_composite_constraint_with_plugin_scen_nulls'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(test_id=None), fields=('name', 'args', 'plugin', 'scenario'), name='unique_item_composite_constraint_with_id_null'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(scenario=None), fields=('name', 'args', 'plugin', 'test_id'), name='unique_item_composite_constraint_with_scen_null'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(plugin=None), fields=('name', 'args', 'scenario', 'test_id'), name='unique_item_composite_constraint_with_plugin_null'),
        )
    ]
