# Generated by Django 3.1.1 on 2020-09-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_verifier', '0010_auto_20200908_0942'),
        ('api', '0013_auto_20200909_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuremappingrule',
            name='codec',
        ),
        migrations.AddField(
            model_name='featuremapping',
            name='codec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_verifier.codec'),
            preserve_default=False,
        ),
    ]
