# Generated by Django 3.1.1 on 2020-09-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200915_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='force_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importjob',
            name='force_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importjob',
            name='site_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
