# Generated by Django 3.1.1 on 2020-10-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_historicalresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('self_url', models.CharField(max_length=255, null=True)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('product', models.CharField(max_length=255, null=True)),
                ('closed_reason', models.CharField(max_length=255, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('oses', models.JSONField()),
                ('exposure', models.CharField(max_length=255, null=True)),
                ('components', models.JSONField()),
                ('platforms', models.JSONField()),
            ],
        ),
    ]
