# Generated by Django 3.1.1 on 2020-10-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_result_changed_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuremappingrule',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
