# Generated by Django 3.1.1 on 2020-10-21 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_featuremappingrule_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuremappingrule',
            options={'ordering': ['milestone__name']},
        ),
        migrations.AlterField(
            model_name='featuremappingrule',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.featuremapping'),
        ),
        migrations.CreateModel(
            name='MergeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('done', 'Done')], default='pending', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('site_url', models.CharField(max_length=255)),
                ('strategy', models.CharField(max_length=255)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
