# Generated by Django 3.1.1 on 2020-10-21 14:52

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_mergejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='blocked',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validation',
            name='canceled',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validation',
            name='error',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validation',
            name='failed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validation',
            name='passed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validation',
            name='skipped',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.validation'),
        ),
    ]
