# Generated by Django 3.1.2 on 2020-10-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_validation_status_counters'),
    ]

    operations = [
        migrations.AlterField(
                model_name='driver',
                name='build_id',
                field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('updated_date', models.DateTimeField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalresult',
            name='kernel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.kernel'),
        ),
        migrations.AddField(
            model_name='result',
            name='kernel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kernel'),
        ),
    ]