# Generated by Django 3.1.1 on 2020-10-31 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_add_kernel_and_change_driver_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kernel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='validation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to=settings.AUTH_USER_MODEL),
        ),
    ]
