# Generated by Django 3.1.1 on 2020-11-11 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_clonejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='validation',
            name='components',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='validation',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='result',
            name='features',
            field=models.ManyToManyField(blank=True, to='api.ResultFeature'),
        ),
    ]
