# Generated by Django 3.1.1 on 2020-11-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_resultfeature_model_and_components_and_features_fields_to_validation_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('name', 'build_id'), name='unique_driver_composite_constraint'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(build_id=None), fields=('name',), name='unique_driver_composite_constraint_with_build_id_null'),
        ),
    ]
