# Generated by Django 3.1.1 on 2020-11-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_unique_together_to_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultGroup',
        ),
        migrations.RemoveField(
            model_name='resultgroupmask',
            name='group',
        ),
        migrations.RemoveConstraint(
            model_name='action',
            name='unique_action_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='group',
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(default='compare', max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='ResultGroupMask',
        ),
        migrations.DeleteModel(
            name='ResultGroupNew',
        ),
    ]
