# Generated by Django 3.1.1 on 2020-12-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_scenario_url_to_result'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='validation',
            name='unique_validation_composite_constraint',
        ),
        migrations.RemoveField(
            model_name='validation',
            name='ignore',
        ),
        migrations.AddField(
            model_name='validation',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='validation',
            constraint=models.UniqueConstraint(fields=('name', 'env', 'platform', 'os', 'deleted'), name='unique_validation_composite_constraint'),
        ),
        migrations.AddConstraint(
            model_name='validation',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('name', 'env', 'platform', 'os'), name='unique_validation_composite_constraint_w_empty_deleted'),
        ),
    ]
