# Generated by Django 3.1.1 on 2020-12-02 13:07

import api.models.validation
from django.db import migrations, models
import django.db.models.deletion


def create_default_valtype(apps, schema_editor):
    ValidationType = apps.get_model("api", "ValidationType")
    ValidationType.objects.create(name=api.models.validation.DEFAULT_VAL_TYPE_NAME)


def remove_default_valtype(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_deleted_validation_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RunPython(create_default_valtype, remove_default_valtype),
        migrations.AddField(
            model_name='validation',
            name='type',
            field=models.ForeignKey(default=api.models.validation.get_default_valtype_id,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='api.validationtype'),
        ),
    ]
