# Generated by Django 3.0.4 on 2020-07-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_verifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfeature',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_verifier.FeatureCategory'),
        ),
        migrations.AlterField(
            model_name='subfeature',
            name='codec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_verifier.Codec'),
        ),
        migrations.AlterField(
            model_name='subfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_verifier.Feature'),
        ),
    ]
