# Generated by Django 3.0.4 on 2020-08-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feature_mapping_table'),
        ('test_verifier', '0002_auto_20200730_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfeature',
            name='lin_platforms',
            field=models.ManyToManyField(blank=True, related_name='lin_subfeatures', to='api.Platform'),
        ),
        migrations.AlterField(
            model_name='subfeature',
            name='win_platforms',
            field=models.ManyToManyField(blank=True, related_name='win_subfeatures', to='api.Platform'),
        ),
    ]
