# Generated by Django 3.0.4 on 2020-08-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_verifier', '0003_auto_20200813_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurecategory',
            options={'verbose_name_plural': 'Feature categories'},
        ),
    ]
