# Generated by Django 3.0.4 on 2020-08-28 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from utils.api_helpers import get_default_owner


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_verifier', '0004_auto_20200817_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='subfeature',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfeature',
            name='created_by',
            field=models.ForeignKey(default=get_default_owner, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='created_subfeatures', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfeature',
            name='imported',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfeature',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subfeature',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='updated_subfeatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
