# Generated by Django 3.0.8 on 2020-09-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_feature_mapping_codec_and_ids'),
        ('test_verifier', '0005_auto_20200828_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurecategory',
            options={'verbose_name_plural': 'Feature Categories'},
        ),
        migrations.RemoveConstraint(
            model_name='subfeature',
            name='unique_subfeature',
        ),
        migrations.AddField(
            model_name='subfeature',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Component'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subfeature',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='subfeature',
            constraint=models.UniqueConstraint(fields=('name', 'category', 'feature', 'codec', 'component'), name='unique_subfeature'),
        ),
    ]
