# Generated by Django 3.0.8 on 2020-09-02 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_verifier', '0006_auto_20200901_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plink', models.CharField(default='or', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rule_grops', to=settings.AUTH_USER_MODEL)),
                ('subfeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_verifier.SubFeature')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_rule_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('rule_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='test_verifier.RuleGroup')),
            ],
        ),
    ]
