# Generated by Django 3.0.4 on 2020-09-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_verifier', '0007_rule_rulegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfeature',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
