# Generated by Django 3.0.4 on 2020-09-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_verifier', '0008_auto_20200903_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfeature',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='updated_subfeatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
