# Generated by Django 3.0.4 on 2020-03-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200312_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='hash_last',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
