# Generated by Django 3.0.4 on 2020-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_result_subsystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='subsystem',
        ),
        migrations.AddField(
            model_name='validation',
            name='subsystem',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (1, 'valib'), (9, 'DirectX 9'), (11, 'DirectX 11')], null=True),
        ),
    ]
