# Generated by Django 3.0.4 on 2020-06-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200616_1016'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(fields=('name', 'session'), name='unique_run_composite_constraint'),
        ),
    ]
