# Generated by Django 3.0.4 on 2020-06-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200622_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
