# Generated by Django 3.0.4 on 2020-06-25 10:11

from django.db import migrations


NEW_VALUES = {
    "Windows 10 RS5": 5,
    "Windows 10 RS4": 4,
    "Windows 10 RS2": 2,
    "Windows 10 RS3": 3,
    "Windows 10 RS1": 1,
    "Windows 10 19H2": 192,
    "Windows 10 19H1": 191,
    "Windows 10 20H1": 201,
    "Ubuntu 16.04": 1604,
    "Ubuntu 18.04": 1804,
    "Ubuntu 19.04": 1904,
    "CentOS": 0,
    "linux.centos_7_4.x64": 0,
    "Windows 10_broken": 0,
}


def add_weight(apps, schema_editor):
    Os = apps.get_model('api', 'os')
    for name, weight in NEW_VALUES.items():
        os = Os.objects.get(name=name)
        os.weight = weight
        os.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_os_weight'),
    ]
    operations = [
        migrations.RunPython(add_weight)
    ]
