# Generated by Django 3.0.4 on 2020-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200625_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='shortcut',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='os',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_os_name'),
        ),
        migrations.AddConstraint(
            model_name='os',
            constraint=models.UniqueConstraint(fields=('shortcut',), name='unique_os_shortcut'),
        ),
    ]
