# Generated by Django 3.0.4 on 2020-06-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200625_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('aliases', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddConstraint(
            model_name='osgroup',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_os_group_name'),
        ),
    ]
